export const authConstants ={
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
}
export const blogConstants = {

    GET_ALL_BLOG_REQUEST:'GET_ALL_BLOG_REQUEST',
    GET_ALL_BLOG_SUCCESS:'GET_ALL_BLOG_SUCCESS',
    GET_ALL_BLOG_FAILURE:'GET_ALL_BLOG_FAILURE',

    
}
export const commentConstants={
    GET_ALL_COMMENT_REQUEST:'GET_ALL_COMMENT_REQUEST',
    GET_ALL_COMMENT_SUCCESS:'GET_ALL_COMMENT_SUCCESS',
    GET_ALL_COMMENT_FAILURE:'GET_ALL_COMMENT_FAILURE',

    ADD_COMMENT_REQUEST:'ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS:'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE:'ADD_COMMENT_FAILURE',
}